App/home/home_blueprints.py
"""Logged-in page routes."""
from flask import Blueprint, render_template
from flask_login import current_user, login_required
from flask import Flask, render_template, request, session, redirect, url_for
from flask_socketio import join_room, leave_room, send, SocketIO
import random
from string import ascii_uppercase
from app import socketio

# Reference for socketio
# https://flask-socketio.readthedocs.io/en/latest/


# The Configuration
home_blueprints = Blueprint(
    "home_blueprints", __name__, template_folder="templates", static_folder="static"
)

rooms = {}


def generate_unique_code(length):
    while True:
        code = ""
        for _ in range(length):
            code += random.choice(ascii_uppercase)

        if code not in rooms:
            break

    return code


@home_blueprints.route("/", methods=["POST", "GET"])
@login_required
def home():
    # session.clear()
    if request.method == "POST":
        name = request.form.get("name")
        code = request.form.get("code")
        join = request.form.get("join", False)
        create = request.form.get("create", False)

        if not name:
            return render_template("home.html", error="Please enter a name.", code=code, name=name)

        if join != False and not code:
            return render_template("home.html", error="Please enter a room code.", code=code, name=name)

        room = code
        if create != False:
            room = generate_unique_code(4)
            rooms[room] = {"members": 0, "messages": []}
        elif code not in rooms:
            return render_template("home.html", error="That room does not exist.", code=code, name=name)

        session["room"] = room
        session["name"] = name
        return redirect(url_for("home_blueprints.room"))

    return render_template("home.html")


@home_blueprints.route("/room")
def room():
    room = session.get("room")
    if room is None or session.get("name") is None or room not in rooms:
        return redirect(url_for("home_blueprints.home"))

    return render_template("room.html", code=room, messages=rooms[room]["messages"])


@socketio.on("message")
def message(data):
    room = session.get("room")
    if room not in rooms:
        return

    content = {
        "name": session.get("name"),
        "message": data["data"]
    }
    send(content, to=room)
    rooms[room]["messages"].append(content)
    print(f"{session.get('name')} said: {data['data']}")


@socketio.on("connect")
def connect(auth):
    room = session.get("room")
    name = session.get("name")
    if not room or not name:
        return
    if room not in rooms:
        leave_room(room)
        return

    join_room(room)
    send({"name": name, "message": "has entered the room"}, to=room)
    rooms[room]["members"] += 1
    print(f"{name} joined room {room}")


@socketio.on("disconnect")
def disconnect():
    room = session.get("room")
    name = session.get("name")
    leave_room(room)

    if room in rooms:
        rooms[room]["members"] -= 1
        if rooms[room]["members"] <= 0:
            del rooms[room]

    send({"name": name, "message": "has left the room"}, to=room)
    print(f"{name} has left the room {room}")

App/login/login_blueprints.py
"""Routes for user authentication."""
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_user, login_required, logout_user

from app import login_manager
from app.login.login_form import LoginForm
from app.signup.signup_models import User

# Blueprint Configuration
login_blueprints = Blueprint("login_blueprints", __name__, template_folder="templates", static_folder="static")


@login_blueprints.route("/login", methods=["GET", "POST"])
def login():
    """
    Log-in page for registered users.

    GET requests serve Login page.
    POST requests validate and redirect user to dashboard.
    """
    # Bypass if user is logged in
    if current_user.is_authenticated:
        return redirect(url_for("home_blueprints.home"))

    form = LoginForm()
    # Validate login attempt
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.check_password(password=form.password.data):
            login_user(user)
            next_page = request.args.get("next")
            return redirect(next_page or url_for("home_blueprints.home"))
        flash("Invalid username/password combination")
        return redirect(url_for("login_blueprints.login"))
    return render_template(
        "login.html",
        form=form,
        title="Log in.",
        template="login-page",
        body="Log in with your User account.",
    )


@login_blueprints.route("/logout")
@login_required
def logout():
    """User log-out logic."""
    logout_user()
    return redirect(url_for("login_blueprints.login"))


@login_manager.user_loader
def load_user(user_id):
    """Check if user is logged-in upon page load."""
    if user_id is not None:
        return User.query.get(user_id)
    return None


@login_manager.unauthorized_handler
def unauthorized():
    """Redirect unauthorized users to Login page."""
    flash("You must be logged in to view that page.")
    return redirect(url_for("login_blueprints.login"))

App/signup/signup_blueprints.py
"""Routes for user authentication."""
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_user

from app import login_manager
from app.signup.signup_form import SignupForm
from app.signup.signup_models import User, db

# Blueprint Configuration
signup_blueprints = Blueprint("signup_blueprints", __name__, template_folder="templates", static_folder="static")


@signup_blueprints.route("/signup", methods=["GET", "POST"])
def signup():
    """
    User sign-up page.

    GET requests serve sign-up page.
    POST requests validate form & user creation.
    """
    form = SignupForm()
    if form.validate_on_submit():
        existing_user = User.query.filter_by(email=form.email.data).first()
        if existing_user is None:
            user = User(
                name=form.name.data, email=form.email.data
            )
            user.set_password(form.password.data)
            db.session.add(user)
            db.session.commit()  # Create new user
            login_user(user)  # Log in as newly created user
            return redirect(url_for("home_blueprints.home"))
        flash("A user already exists with that email address.")
    return render_template(
        "signup.html",
        title="Create an Account.",
        form=form,
        template="signup-page",
        body="Sign up for a user account.",
    )


@login_manager.user_loader
def load_user(user_id):
    """Check if user is logged-in upon page load."""
    if user_id is not None:
        return User.query.get(user_id)
    return None


@login_manager.unauthorized_handler
def unauthorized():
    """Redirect unauthorized users to the login page."""
    flash("You must be logged in to access this page.")
    return redirect(url_for("login_blueprints.login"))

App/templates/analytics.jinja2
<script type="text/javascript">
  var _gauges = _gauges || [];
  (function() {
    var t   = document.createElement('script');
    t.type  = 'text/javascript';
    t.async = true;
    t.id    = 'gauges-tracker';
    t.setAttribute('data-site-id', '5eb66f54d96b5b0e0ead80ed');
    t.setAttribute('data-track-path', 'https://track.gaug.es/track.gif');
    t.src = 'https://d2fuc4clr7gvcn.cloudfront.net/track.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(t, s);
  })();
</script>

App/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Pharmceutical-Healthcare Providers Chat App</title>
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='csss/style.css')}}"
    />
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"
      integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA=="
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <div class="content">{% block content %} {% endblock %}</div>
  </body>
</html>

App/templates/credentialsbase.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{{url_for('static', filename='images/icons/favicon.ico')}}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='fonts/font-awesome-4.7.0/css/font-awesome.min.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='fonts/Linearicons-Free-v1.0.0/icon-font.min.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='vendor/animate/animate.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='vendor/css-hamburgers/hamburgers.min.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='vendor/animsition/css/animsition.min.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='vendor/select2/select2.min.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='vendor/daterangepicker/daterangepicker.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/util.css')}}">
	<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/main.css')}}">
<!--===============================================================================================-->
</head>
<body style="background-color: #666666;">



{% block content %}
{% endblock %}



<!--===============================================================================================-->
	<script src="{{url_for('static', filename='vendor/jquery/jquery-3.2.1.min.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url_for('static', filename='vendor/animsition/js/animsition.min.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url_for('static', filename='vendor/bootstrap/js/popper.js')}}"></script>
	<script src="{{url_for('static', filename='vendor/bootstrap/js/bootstrap.min.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url_for('static', filename='vendor/select2/select2.min.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url_for('static', filename='vendor/daterangepicker/moment.min.js')}}"></script>
	<script src="{{url_for('static', filename='vendor/daterangepicker/daterangepicker.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url_for('static', filename='vendor/countdowntime/countdowntime.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url_for('static', filename='js/main.js')}}"></script>

</body>
</html>

App/templates/dashboard.jinja2
{% extends "layout.jinja2" %}

{% block pagestyles %}
  <link href="{{ url_for('static', filename='dist/css/dashboard.css') }}" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://use.typekit.net/sus7rlu.css">
{% endblock %}

{% block content %}
  <h1>{{ body }}</h1>

  {% if current_user.is_authenticated %}
    <p>Hi {{ current_user.name }}!</p>
    <a href="{{ url_for('login_blueprints.logout') }}">Log out</a>
  {% endif %}

{% endblock %}

App/templates/home.html
{% extends 'base.html' %} {% block content %}
<form method="post" class="buttons">
  <h3>Welcome to Pharma-Health Chat Room</h3>
<div>
  <label>Name:</label> 
  <input type="text" placeholder="Please input your name" name="name" value="{{name}}" />
</div>
<div class="join">
  No code? Create a room <button type="submit" name="create" class="create-btn">Create</button>
</div>
<div>
  <input type="text" placeholder="Enter Room code to join" name="code" value="{{code}}" />
  <button type="submit" name="join">Join a Room</button>
</div>
  {% if error %}
  <ul>
    <li>{{error}}</li>
  </ul>
  {% endif %}
</form>
{% endblock %}

App/templates/layout.jinja2
<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <title>{{ title }}</title>
  <meta name="description" content="Add user authentication to your Flask app."/>
  <meta name="HandheldFriendly" content="True"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover"/>
  <meta name="theme-color" content="#5eb9d7"/>
  <link rel="shortcut icon" href="{{ url_for('static', filename='dist/img/favicon.png') }}" type="image/x-icon"/>
  <meta property="og:site_name" content="Hackers and Slackers"/>
  <meta property="og:type" content="website"/>
  <meta property="og:title" content="Hackers and Slackers - Hackers and Slackers"/>
  <meta property="og:description" content="Add user authentication to your Flask app."/>
  <meta property="og:url" content="https://flasklogin.hackersandslackers.app/"/>
  <meta name="twitter:title" content="{{ title }}"/>
  <meta name="twitter:description" content="Add user authentication to your Flask app."/>
  <meta name="twitter:url" content="https://flasklogin.hackersandslackers.app/"/>
  <meta name="twitter:site" content="@hackersslackers"/>
  <meta name="twitter:creator" content="@toddrbirchard"/>
  <meta name="twitter:card" content="summary_large_image"/>
  <meta name="twitter:image"
        content=" https://storage.googleapis.com/hackersandslackers-cdn/2019/06/flasklogin@2x.jpg"/>
  <meta property="og:image" content=" https://storage.googleapis.com/hackersandslackers-cdn/2019/06/flasklogin@2x.jpg"/>
  <meta property="og:image:width" content="1000"/>
  <meta property="og:image:height" content="523"/>
  <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,500" rel="stylesheet"/>
  {% block pagestyles %}{% endblock %}
</head>

<body class="{{ template }}">
<div class="container">
  {% block content %}{% endblock %}
</div>
<script src="{{ url_for('static', filename='dist/js/main.min.js') }}"></script>
{% block additionalscripts %}{% endblock %}
{% include 'analytics.jinja2' %}
</body>

</html>

App/templates/login.html
{% extends "credentialsbase.html" %}
{% block content %}
<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form method="POST" action="/login" class="login100-form validate-form">
						{{ form.csrf_token }}

					    {% for message in get_flashed_messages() %}
						  <div class="alert alert-warning">
							<button type="button" class="close" data-dismiss="alert">&times;</button>
							{{ message }}
						  </div>
						{% endfor %}
						<br>
						<span class="login100-form-title p-b-43">
							Welcome to Pharma-Health Login Page
						</span>

							<fieldset class="wrap-input100">
								{{ form.email.label }}
								{{ form.email(class="wrap-input100", placeholder="  Please Enter Email - Username") }}
								{% if form.email.errors %}
								  <ul class="errors">
									{% for error in form.email.errors %}
									  <li>{{ error }}</li>{% endfor %}
								  </ul>
								{% endif %}

							</fieldset>

							<br>

							  <fieldset class="wrap-input100">
								{{ form.password.label }}
								{{ form.password(class="wrap-input100", placeholder="  Enter Password") }}
								{% if form.email.errors %}
								  <ul class="errors">
									{% for error in form.password.errors %}
									  <li>{{ error }}</li>{% endfor %}
								  </ul>
								{% endif %}
							  </fieldset>


						<br>

						<div class="flex-sb-m w-full p-t-3 p-b-32">


							


						<div class="container-login100-form-btn">
							{{ form.submit(class="login100-form-btn") }}
						</div>

						<div class="text-center p-t-46 p-b-20">
							<span class="txt2">
								<p><a href="/signup">sign up </a></p>
							</span>
						</div>

				</form>

			</div>
		</div>
	</div>
{% endblock %}

App/templates/login.jinja2
{% extends "layout.jinja2" %}

{% block pagestyles %}
  <link href="{{ url_for('static', filename='dist/css/account.css') }}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
  <div class="form-wrapper">

    <div class="logo">
      <img src="{{ url_for('static', filename='dist/img/logo.png') }}" alt="logo"/>
    </div>

    {% for message in get_flashed_messages() %}
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
      </div>
    {% endfor %}

    <h1>Log In</h1>

    <form method="POST" action="/login">
      {{ form.csrf_token }}

      <fieldset class="email">
        {{ form.email.label }}
        {{ form.email(placeholder='youremail@example.com') }}
        {% if form.email.errors %}
          <ul class="errors">
            {% for error in form.email.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <fieldset class="password">
        {{ form.password.label }}
        {{ form.password }}
        {% if form.email.errors %}
          <ul class="errors">
            {% for error in form.password.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <div class="submit-button">
        {{ form.submit }}
      </div>

    

    </form>
  </div>
{% endblock %}

App/templates/room.html
{% extends 'base.html' %} {% block content %}
<div class="message-box">
  <h2>Chat Room: {{code}}</h2>
  <div class="messages" id="messages"></div>
  <div class="inputs">
    <input
      type="text"
      rows="3"
      placeholder="Message"
      name="message"
      id="message"
    />
    <button type="button" name="send" id="send-btn" onClick="sendMessage()">
      Send
    </button>
  </div>
</div>
<script type="text/javascript">
  var socketio = io();

  const messages = document.getElementById("messages");

  const createMessage = (name, msg) => {
    const content = `
    <div class="text">
        <span>
            <strong>${name}</strong>: ${msg}
        </span>
        <span class="muted">
            ${new Date().toLocaleString()}
        </span>
    </div>
    `;
    messages.innerHTML += content;
  };

  socketio.on("message", (data) => {
    createMessage(data.name, data.message);
  });

  const sendMessage = () => {
    const message = document.getElementById("message");
    if (message.value == "") return;
    socketio.emit("message", { data: message.value });
    message.value = "";
  };
</script>
{% for msg in messages %}
<script type="text/javascript">
  createMessage("{{msg.name}}", "{{msg.message}}");
</script>
{% endfor %} {% endblock %}

App/templates/signup.html
{% extends "credentialsbase.html" %}
{% block content %}
<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form method="POST" action="/signup" class="login100-form validate-form">
						{{ form.csrf_token }}

					    {% for message in get_flashed_messages() %}
						  <div class="alert alert-warning">
							<button type="button" class="close" data-dismiss="alert">&times;</button>
							{{ message }}
						  </div>
						{% endfor %}

						<br>
						<span class="login100-form-title p-b-43">
							Pharma-Health Registration Page
						</span>

							<fieldset class="wrap-input100">
								{{ form.name.label }}
								{{ form.name(class="wrap-input100", placeholder="  Enter Name ") }}
								{% if form.name.errors %}
								  <ul class="errors">
									{% for error in form.name.errors %}
									  <li>{{ error }}</li>{% endfor %}
								  </ul>
								{% endif %}

							</fieldset><br>

							<fieldset class="wrap-input100">
								{{ form.email.label }}
								{{ form.email(class="wrap-input100", placeholder="  Enter Email - Username") }}
								{% if form.email.errors %}
								  <ul class="errors">
									{% for error in form.email.errors %}
									  <li>{{ error }}</li>{% endfor %}
								  </ul>
								{% endif %}

							</fieldset>

							<br>

							  <fieldset class="wrap-input100">
								{{ form.password.label }}
								{{ form.password(class="wrap-input100", placeholder="  Enter Password") }}
								{% if form.password.errors %}
								  <ul class="errors">
									{% for error in form.password.errors %}
									  <li>{{ error }}</li>{% endfor %}
								  </ul>
								{% endif %}
							  </fieldset>



												<br>

							  <fieldset class="wrap-input100">
								{{ form.confirm.label }}
								{{ form.confirm(class="wrap-input100", placeholder="  Confirm Password") }}
								{% if form.confirm.errors %}
								  <ul class="errors">
									{% for error in form.confirm.errors %}
									  <li>{{ error }}</li>{% endfor %}
								  </ul>
								{% endif %}
							  </fieldset>



						<br>
						<div class="container-login100-form-btn">
							{{ form.submit(class="login100-form-btn") }}
						</div>

					   <div class="text-center p-t-46 p-b-20">
							<span class="txt2">
								<a href="/login">Already Have login</a>
							</span>
						</div>



				</form>
			</div>
		</div>
	</div>
{% endblock %}

App/templates/signup.jinja2
{% extends "layout.jinja2" %}

{% block pagestyles %}
  <link href="{{ url_for('static', filename='dist/css/account.css') }}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
  <div class="form-wrapper">

    <div class="logo">
      <img src="{{ url_for('static', filename='dist/img/logo.png') }}" alt="logo"/>
    </div>

    {% for message in get_flashed_messages() %}
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
      </div>
    {% endfor %}

    <h1>Sign Up</h1>

    <form method="POST" action="/signup">
      {{ form.csrf_token }}

      <fieldset class="name">
        {{ form.name.label }}
        {{ form.name(placeholder='John Smith') }}
        {% if form.name.errors %}
          <ul class="errors">
            {% for error in form.email.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <fieldset class="email">
        {{ form.email.label }}
        {{ form.email(placeholder='youremail@example.com') }}
        {% if form.email.errors %}
          <ul class="errors">
            {% for error in form.email.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <fieldset class="password">
        {{ form.password.label }}
        {{ form.password }}
        {% if form.password.errors %}
          <ul class="errors">
            {% for error in form.password.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <fieldset class="confirm">
        {{ form.confirm.label }}
        {{ form.confirm }}
        {% if form.confirm.errors %}
          <ul class="errors">
            {% for error in form.confirm.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <fieldset class="website">
        {{ form.website.label }}
        {{ form.website(placeholder='http://example.com') }}
      </fieldset>

      <div class="submit-button">
        {{ form.submit }}
      </div>

    </form>

    <div class="login-signup">
      <span>Already have an account? <a href="{{ url_for('login_blueprints.login') }}">Log in.</a></span>
    </div>
  </div>
{% endblock %}